// Code generated by protoc-gen-go.
// source: metadata.proto
// DO NOT EDIT!

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Metadata struct {
	Uuid             *string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Metadata) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*Metadata)(nil), "ketchup.models.Metadata")
}
func (m *Metadata) SetUuid(v *string) {
	m.Uuid = v
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 80 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x49,
	0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcb, 0x4e, 0x2d, 0x49,
	0xce, 0x28, 0x2d, 0xd0, 0xcb, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0x56, 0x92, 0xe3, 0xe2, 0xf0, 0x85,
	0xaa, 0x10, 0x12, 0xe2, 0x62, 0x29, 0x2d, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x02, 0xb3, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x42, 0x9e, 0x7a, 0x40, 0x00, 0x00, 0x00,
}
