#!/bin/bash

source ./scripts/env

export PATH=./node_modules/.bin:${GOPATH}/bin:${PATH}

# send kill to all subprocesses if parent script receives
# SIGNIT/SIGTERM/EXIT. -$$ is the group of this process
# and all child processes
trap "kill -- -$$" SIGINT SIGTERM EXIT

node-sass ${SASS_WATCH} \
  ${SRC_DIR}/css/app.sass \
  ${BUILD_DIR}/app.css &

watchify ${SRC_DIR}/js/app.ts \
  -p tsify \
  --debug \
  --outfile ${BUILD_DIR}/app.js &

( cd build && python -m SimpleHTTPServer 8800 ) &

# wait for kill signal
wait
