// Code generated by protoc-gen-go.
// source: packages.proto
// DO NOT EDIT!

package packages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Package_Type int32

const (
	Package_unknown Package_Type = 0
	Package_theme   Package_Type = 1
	Package_plugin  Package_Type = 2
)

var Package_Type_name = map[int32]string{
	0: "unknown",
	1: "theme",
	2: "plugin",
}
var Package_Type_value = map[string]int32{
	"unknown": 0,
	"theme":   1,
	"plugin":  2,
}

func (x Package_Type) Enum() *Package_Type {
	p := new(Package_Type)
	*p = x
	return p
}
func (x Package_Type) String() string {
	return proto.EnumName(Package_Type_name, int32(x))
}
func (x *Package_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Package_Type_value, data, "Package_Type")
	if err != nil {
		return err
	}
	*x = Package_Type(value)
	return nil
}
func (Package_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{1, 0} }

type PackageAuthor struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email            *string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PackageAuthor) Reset()                    { *m = PackageAuthor{} }
func (m *PackageAuthor) String() string            { return proto.CompactTextString(m) }
func (*PackageAuthor) ProtoMessage()               {}
func (*PackageAuthor) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *PackageAuthor) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PackageAuthor) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

type Package struct {
	Type             *Package_Type    `protobuf:"varint,1,opt,name=type,enum=ketchup.packages.Package_Type" json:"type,omitempty"`
	Name             *string          `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Authors          []*PackageAuthor `protobuf:"bytes,3,rep,name=authors" json:"authors,omitempty"`
	Description      *string          `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Homepage         *string          `protobuf:"bytes,5,opt,name=homepage" json:"homepage,omitempty"`
	Tags             []string         `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty"`
	ReadmeUrl        *string          `protobuf:"bytes,7,opt,name=readme_url,json=readmeUrl" json:"readme_url,omitempty"`
	VcsUrl           *string          `protobuf:"bytes,8,opt,name=vcs_url,json=vcsUrl" json:"vcs_url,omitempty"`
	ScreenshotUrls   []string         `protobuf:"bytes,9,rep,name=screenshot_urls,json=screenshotUrls" json:"screenshot_urls,omitempty"`
	KetchupVersion   *string          `protobuf:"bytes,10,opt,name=ketchup_version,json=ketchupVersion" json:"ketchup_version,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Package) Reset()                    { *m = Package{} }
func (m *Package) String() string            { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()               {}
func (*Package) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *Package) GetType() Package_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Package_unknown
}

func (m *Package) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Package) GetAuthors() []*PackageAuthor {
	if m != nil {
		return m.Authors
	}
	return nil
}

func (m *Package) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Package) GetHomepage() string {
	if m != nil && m.Homepage != nil {
		return *m.Homepage
	}
	return ""
}

func (m *Package) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Package) GetReadmeUrl() string {
	if m != nil && m.ReadmeUrl != nil {
		return *m.ReadmeUrl
	}
	return ""
}

func (m *Package) GetVcsUrl() string {
	if m != nil && m.VcsUrl != nil {
		return *m.VcsUrl
	}
	return ""
}

func (m *Package) GetScreenshotUrls() []string {
	if m != nil {
		return m.ScreenshotUrls
	}
	return nil
}

func (m *Package) GetKetchupVersion() string {
	if m != nil && m.KetchupVersion != nil {
		return *m.KetchupVersion
	}
	return ""
}

type Registry struct {
	RegistryVersion  *string    `protobuf:"bytes,1,opt,name=registry_version,json=registryVersion" json:"registry_version,omitempty"`
	KetchupMin       *string    `protobuf:"bytes,2,opt,name=ketchup_min,json=ketchupMin" json:"ketchup_min,omitempty"`
	Packages         []*Package `protobuf:"bytes,10,rep,name=packages" json:"packages,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Registry) Reset()                    { *m = Registry{} }
func (m *Registry) String() string            { return proto.CompactTextString(m) }
func (*Registry) ProtoMessage()               {}
func (*Registry) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

func (m *Registry) GetRegistryVersion() string {
	if m != nil && m.RegistryVersion != nil {
		return *m.RegistryVersion
	}
	return ""
}

func (m *Registry) GetKetchupMin() string {
	if m != nil && m.KetchupMin != nil {
		return *m.KetchupMin
	}
	return ""
}

func (m *Registry) GetPackages() []*Package {
	if m != nil {
		return m.Packages
	}
	return nil
}

func init() {
	proto.RegisterType((*PackageAuthor)(nil), "ketchup.packages.PackageAuthor")
	proto.RegisterType((*Package)(nil), "ketchup.packages.Package")
	proto.RegisterType((*Registry)(nil), "ketchup.packages.Registry")
	proto.RegisterEnum("ketchup.packages.Package_Type", Package_Type_name, Package_Type_value)
}
func (m *PackageAuthor) SetName(v *string) {
	m.Name = v
}

func (m *PackageAuthor) SetEmail(v *string) {
	m.Email = v
}

func (m *Package) SetType(v *Package_Type) {
	m.Type = v
}

func (m *Package) SetName(v *string) {
	m.Name = v
}

func (m *Package) SetAuthors(v []*PackageAuthor) {
	m.Authors = v
}

func (m *Package) SetDescription(v *string) {
	m.Description = v
}

func (m *Package) SetHomepage(v *string) {
	m.Homepage = v
}

func (m *Package) SetTags(v []string) {
	m.Tags = v
}

func (m *Package) SetReadmeUrl(v *string) {
	m.ReadmeUrl = v
}

func (m *Package) SetVcsUrl(v *string) {
	m.VcsUrl = v
}

func (m *Package) SetScreenshotUrls(v []string) {
	m.ScreenshotUrls = v
}

func (m *Package) SetKetchupVersion(v *string) {
	m.KetchupVersion = v
}

func (m *Registry) SetRegistryVersion(v *string) {
	m.RegistryVersion = v
}

func (m *Registry) SetKetchupMin(v *string) {
	m.KetchupMin = v
}

func (m *Registry) SetPackages(v []*Package) {
	m.Packages = v
}

func init() { proto.RegisterFile("packages.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xc1, 0xaa, 0x9b, 0x40,
	0x14, 0xad, 0xd1, 0x44, 0xbd, 0x52, 0x9f, 0x0c, 0x85, 0x4e, 0x0b, 0xed, 0x13, 0x37, 0x7d, 0xed,
	0xc2, 0x45, 0xa0, 0x8b, 0xb7, 0xec, 0x07, 0x14, 0x8a, 0x34, 0xdd, 0x86, 0xc1, 0x5c, 0x54, 0xa2,
	0xe3, 0x30, 0x33, 0xa6, 0xe4, 0x23, 0xba, 0xeb, 0x07, 0x97, 0x19, 0x47, 0x1b, 0x1e, 0x64, 0x77,
	0xe7, 0x9c, 0x73, 0xef, 0x39, 0x7a, 0x20, 0x15, 0xac, 0x3e, 0xb3, 0x06, 0x55, 0x29, 0xe4, 0xa8,
	0x47, 0x92, 0x9d, 0x51, 0xd7, 0xed, 0x24, 0xca, 0x05, 0x2f, 0x9e, 0xe1, 0xf5, 0x8f, 0x79, 0xfe,
	0x36, 0xe9, 0x76, 0x94, 0x84, 0x40, 0xc0, 0xd9, 0x80, 0xd4, 0xcb, 0xbd, 0xa7, 0xb8, 0xb2, 0x33,
	0x79, 0x03, 0x5b, 0x1c, 0x58, 0xd7, 0xd3, 0x8d, 0x05, 0xe7, 0x47, 0xf1, 0xd7, 0x87, 0xd0, 0xed,
	0x92, 0x3d, 0x04, 0xfa, 0x2a, 0xe6, 0xad, 0x74, 0xff, 0xb1, 0x7c, 0xe9, 0x53, 0x3a, 0x61, 0xf9,
	0xf3, 0x2a, 0xb0, 0xb2, 0xda, 0xd5, 0x69, 0x73, 0xe3, 0xf4, 0x0c, 0x21, 0xb3, 0x39, 0x14, 0xf5,
	0x73, 0xff, 0x29, 0xd9, 0x3f, 0xde, 0x3d, 0x35, 0xe7, 0xad, 0x16, 0x3d, 0xc9, 0x21, 0x39, 0xa1,
	0xaa, 0x65, 0x27, 0x74, 0x37, 0x72, 0x1a, 0xd8, 0xab, 0xb7, 0x10, 0x79, 0x0f, 0x51, 0x3b, 0x0e,
	0x28, 0x58, 0x83, 0x74, 0x6b, 0xe9, 0xf5, 0x6d, 0xc2, 0x68, 0xd6, 0x28, 0xba, 0xcb, 0x7d, 0x13,
	0xc6, 0xcc, 0xe4, 0x03, 0x80, 0x44, 0x76, 0x1a, 0xf0, 0x38, 0xc9, 0x9e, 0x86, 0x76, 0x23, 0x9e,
	0x91, 0x83, 0xec, 0xc9, 0x5b, 0x08, 0x2f, 0xb5, 0xb2, 0x5c, 0x64, 0xb9, 0xdd, 0xa5, 0x56, 0x86,
	0xf8, 0x04, 0x0f, 0xaa, 0x96, 0x88, 0x5c, 0xb5, 0xa3, 0x36, 0xbc, 0xa2, 0xb1, 0x3d, 0x9b, 0xfe,
	0x87, 0x0f, 0xb2, 0x57, 0x46, 0xe8, 0xbe, 0xee, 0x78, 0x41, 0xa9, 0x4c, 0x6c, 0xb0, 0x97, 0x52,
	0x07, 0xff, 0x9a, 0xd1, 0xe2, 0x0b, 0x04, 0xe6, 0xc7, 0x91, 0x04, 0xc2, 0x89, 0x9f, 0xf9, 0xf8,
	0x9b, 0x67, 0xaf, 0x48, 0x0c, 0x5b, 0xdd, 0xe2, 0x80, 0x99, 0x47, 0x00, 0x76, 0xa2, 0x9f, 0x9a,
	0x8e, 0x67, 0x9b, 0xe2, 0x8f, 0x07, 0x51, 0x85, 0x4d, 0xa7, 0xb4, 0xbc, 0x92, 0xcf, 0x90, 0x49,
	0x37, 0xaf, 0x16, 0x73, 0xb3, 0x0f, 0x0b, 0xee, 0x3c, 0xc8, 0x23, 0x24, 0x4b, 0x98, 0xa1, 0xe3,
	0xae, 0x15, 0x70, 0xd0, 0xf7, 0x8e, 0x93, 0xaf, 0x10, 0x2d, 0x1d, 0x50, 0xb0, 0xe5, 0xbc, 0xbb,
	0x5b, 0x4e, 0xb5, 0x4a, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xd1, 0x8e, 0x3a, 0x84, 0x02,
	0x00, 0x00,
}
