// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto
	content.proto
	data.proto
	export/export.proto
	metadata.proto
	page.proto
	route.proto
	theme.proto
	user.proto
	packages.proto
	struct.proto

It has these top-level messages:
	Error
	FieldError
	ListOptions
	UpdatePageRoutesRequest
	GetRenderedPageRequest
	GetRenderedPageResponse
	ListPageRequest
	ListPageResponse
	ListRouteRequest
	ListRouteResponse
	ListThemeResponse
	GetThemeResponse
	UpdateDataRequest
	ListDataResponse
	TLSSettingsResponse
	EnableTLSRequest
	CheckThemeForUpdateResponse
	InstallThemeRequest
	UpdateThemeRequest
	ContentMultiple
	ContentText
	ContentString
	Data
	Export
	Metadata
	Timestamp
	Author
	Page
	Content
	Route
	Theme
	ThemeTemplate
	ThemePlaceholder
	ThemeAsset
	User
	PackageAuthor
	Package
	Registry
	Struct
	Value
	ListValue
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import ketchup_models "github.com/ketchuphq/ketchup/proto/ketchup/models"
import structpb "github.com/ketchuphq/ketchup/proto/structpb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_INTERNAL_SERVER_ERROR ErrorCode = 1
	ErrorCode_NOT_FOUND             ErrorCode = 2
	ErrorCode_FORBIDDEN             ErrorCode = 3
)

var ErrorCode_name = map[int32]string{
	1: "INTERNAL_SERVER_ERROR",
	2: "NOT_FOUND",
	3: "FORBIDDEN",
}
var ErrorCode_value = map[string]int32{
	"INTERNAL_SERVER_ERROR": 1,
	"NOT_FOUND":             2,
	"FORBIDDEN":             3,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetRenderedPageRequest_RenderedPageFilter int32

const (
	GetRenderedPageRequest_all       GetRenderedPageRequest_RenderedPageFilter = 1
	GetRenderedPageRequest_published GetRenderedPageRequest_RenderedPageFilter = 2
	GetRenderedPageRequest_draft     GetRenderedPageRequest_RenderedPageFilter = 3
)

var GetRenderedPageRequest_RenderedPageFilter_name = map[int32]string{
	1: "all",
	2: "published",
	3: "draft",
}
var GetRenderedPageRequest_RenderedPageFilter_value = map[string]int32{
	"all":       1,
	"published": 2,
	"draft":     3,
}

func (x GetRenderedPageRequest_RenderedPageFilter) Enum() *GetRenderedPageRequest_RenderedPageFilter {
	p := new(GetRenderedPageRequest_RenderedPageFilter)
	*p = x
	return p
}
func (x GetRenderedPageRequest_RenderedPageFilter) String() string {
	return proto.EnumName(GetRenderedPageRequest_RenderedPageFilter_name, int32(x))
}
func (x *GetRenderedPageRequest_RenderedPageFilter) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetRenderedPageRequest_RenderedPageFilter_value, data, "GetRenderedPageRequest_RenderedPageFilter")
	if err != nil {
		return err
	}
	*x = GetRenderedPageRequest_RenderedPageFilter(value)
	return nil
}
func (GetRenderedPageRequest_RenderedPageFilter) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

type ListPageRequest_ListPageFilter int32

const (
	ListPageRequest_all       ListPageRequest_ListPageFilter = 1
	ListPageRequest_published ListPageRequest_ListPageFilter = 2
	ListPageRequest_draft     ListPageRequest_ListPageFilter = 3
)

var ListPageRequest_ListPageFilter_name = map[int32]string{
	1: "all",
	2: "published",
	3: "draft",
}
var ListPageRequest_ListPageFilter_value = map[string]int32{
	"all":       1,
	"published": 2,
	"draft":     3,
}

func (x ListPageRequest_ListPageFilter) Enum() *ListPageRequest_ListPageFilter {
	p := new(ListPageRequest_ListPageFilter)
	*p = x
	return p
}
func (x ListPageRequest_ListPageFilter) String() string {
	return proto.EnumName(ListPageRequest_ListPageFilter_name, int32(x))
}
func (x *ListPageRequest_ListPageFilter) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ListPageRequest_ListPageFilter_value, data, "ListPageRequest_ListPageFilter")
	if err != nil {
		return err
	}
	*x = ListPageRequest_ListPageFilter(value)
	return nil
}
func (ListPageRequest_ListPageFilter) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

type Error struct {
	Code             *ErrorCode    `protobuf:"varint,1,opt,name=code,enum=ketchup.api.ErrorCode" json:"code,omitempty"`
	Title            *string       `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Detail           *string       `protobuf:"bytes,3,opt,name=detail" json:"detail,omitempty"`
	Fields           []*FieldError `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetCode() ErrorCode {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ErrorCode_INTERNAL_SERVER_ERROR
}

func (m *Error) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Error) GetDetail() string {
	if m != nil && m.Detail != nil {
		return *m.Detail
	}
	return ""
}

func (m *Error) GetFields() []*FieldError {
	if m != nil {
		return m.Fields
	}
	return nil
}

type FieldError struct {
	Field            *string `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Code             *string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Title            *string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Detail           *string `protobuf:"bytes,4,opt,name=detail" json:"detail,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FieldError) Reset()                    { *m = FieldError{} }
func (m *FieldError) String() string            { return proto.CompactTextString(m) }
func (*FieldError) ProtoMessage()               {}
func (*FieldError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FieldError) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

func (m *FieldError) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *FieldError) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *FieldError) GetDetail() string {
	if m != nil && m.Detail != nil {
		return *m.Detail
	}
	return ""
}

type ListOptions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ListOptions) Reset()                    { *m = ListOptions{} }
func (m *ListOptions) String() string            { return proto.CompactTextString(m) }
func (*ListOptions) ProtoMessage()               {}
func (*ListOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type UpdatePageRoutesRequest struct {
	Routes           []*ketchup_models.Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *UpdatePageRoutesRequest) Reset()                    { *m = UpdatePageRoutesRequest{} }
func (m *UpdatePageRoutesRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePageRoutesRequest) ProtoMessage()               {}
func (*UpdatePageRoutesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdatePageRoutesRequest) GetRoutes() []*ketchup_models.Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type GetRenderedPageRequest struct {
	Options          *GetRenderedPageRequest_RenderedPageOptions `protobuf:"bytes,1,opt,name=options" json:"options,omitempty"`
	XXX_unrecognized []byte                                      `json:"-"`
}

func (m *GetRenderedPageRequest) Reset()                    { *m = GetRenderedPageRequest{} }
func (m *GetRenderedPageRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRenderedPageRequest) ProtoMessage()               {}
func (*GetRenderedPageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetRenderedPageRequest) GetOptions() *GetRenderedPageRequest_RenderedPageOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type GetRenderedPageRequest_RenderedPageOptions struct {
	Filter           *GetRenderedPageRequest_RenderedPageFilter `protobuf:"varint,1,opt,name=filter,enum=ketchup.api.GetRenderedPageRequest_RenderedPageFilter" json:"filter,omitempty"`
	XXX_unrecognized []byte                                     `json:"-"`
}

func (m *GetRenderedPageRequest_RenderedPageOptions) Reset() {
	*m = GetRenderedPageRequest_RenderedPageOptions{}
}
func (m *GetRenderedPageRequest_RenderedPageOptions) String() string {
	return proto.CompactTextString(m)
}
func (*GetRenderedPageRequest_RenderedPageOptions) ProtoMessage() {}
func (*GetRenderedPageRequest_RenderedPageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

func (m *GetRenderedPageRequest_RenderedPageOptions) GetFilter() GetRenderedPageRequest_RenderedPageFilter {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return GetRenderedPageRequest_all
}

type GetRenderedPageResponse struct {
	Data             *structpb.Struct `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GetRenderedPageResponse) Reset()                    { *m = GetRenderedPageResponse{} }
func (m *GetRenderedPageResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRenderedPageResponse) ProtoMessage()               {}
func (*GetRenderedPageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetRenderedPageResponse) GetData() *structpb.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListPageRequest struct {
	List             *ListOptions                     `protobuf:"bytes,1,opt,name=list" json:"list,omitempty"`
	Options          *ListPageRequest_ListPageOptions `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *ListPageRequest) Reset()                    { *m = ListPageRequest{} }
func (m *ListPageRequest) String() string            { return proto.CompactTextString(m) }
func (*ListPageRequest) ProtoMessage()               {}
func (*ListPageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ListPageRequest) GetList() *ListOptions {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ListPageRequest) GetOptions() *ListPageRequest_ListPageOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type ListPageRequest_ListPageOptions struct {
	Filter           *ListPageRequest_ListPageFilter `protobuf:"varint,1,opt,name=filter,enum=ketchup.api.ListPageRequest_ListPageFilter" json:"filter,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *ListPageRequest_ListPageOptions) Reset()         { *m = ListPageRequest_ListPageOptions{} }
func (m *ListPageRequest_ListPageOptions) String() string { return proto.CompactTextString(m) }
func (*ListPageRequest_ListPageOptions) ProtoMessage()    {}
func (*ListPageRequest_ListPageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

func (m *ListPageRequest_ListPageOptions) GetFilter() ListPageRequest_ListPageFilter {
	if m != nil && m.Filter != nil {
		return *m.Filter
	}
	return ListPageRequest_all
}

type ListPageResponse struct {
	Pages            []*ketchup_models.Page `protobuf:"bytes,1,rep,name=pages" json:"pages,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *ListPageResponse) Reset()                    { *m = ListPageResponse{} }
func (m *ListPageResponse) String() string            { return proto.CompactTextString(m) }
func (*ListPageResponse) ProtoMessage()               {}
func (*ListPageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListPageResponse) GetPages() []*ketchup_models.Page {
	if m != nil {
		return m.Pages
	}
	return nil
}

type ListRouteRequest struct {
	List             *ListOptions                       `protobuf:"bytes,1,opt,name=list" json:"list,omitempty"`
	Options          *ListRouteRequest_ListRouteOptions `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *ListRouteRequest) Reset()                    { *m = ListRouteRequest{} }
func (m *ListRouteRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRouteRequest) ProtoMessage()               {}
func (*ListRouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListRouteRequest) GetList() *ListOptions {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ListRouteRequest) GetOptions() *ListRouteRequest_ListRouteOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type ListRouteRequest_ListRouteOptions struct {
	PageUuid         *string `protobuf:"bytes,1,opt,name=page_uuid,json=pageUuid" json:"page_uuid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ListRouteRequest_ListRouteOptions) Reset()         { *m = ListRouteRequest_ListRouteOptions{} }
func (m *ListRouteRequest_ListRouteOptions) String() string { return proto.CompactTextString(m) }
func (*ListRouteRequest_ListRouteOptions) ProtoMessage()    {}
func (*ListRouteRequest_ListRouteOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0}
}

func (m *ListRouteRequest_ListRouteOptions) GetPageUuid() string {
	if m != nil && m.PageUuid != nil {
		return *m.PageUuid
	}
	return ""
}

type ListRouteResponse struct {
	Routes           []*ketchup_models.Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ListRouteResponse) Reset()                    { *m = ListRouteResponse{} }
func (m *ListRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*ListRouteResponse) ProtoMessage()               {}
func (*ListRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ListRouteResponse) GetRoutes() []*ketchup_models.Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type ListThemeResponse struct {
	Themes           []*ketchup_models.Theme `protobuf:"bytes,1,rep,name=themes" json:"themes,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ListThemeResponse) Reset()                    { *m = ListThemeResponse{} }
func (m *ListThemeResponse) String() string            { return proto.CompactTextString(m) }
func (*ListThemeResponse) ProtoMessage()               {}
func (*ListThemeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ListThemeResponse) GetThemes() []*ketchup_models.Theme {
	if m != nil {
		return m.Themes
	}
	return nil
}

type GetThemeResponse struct {
	Theme            *ketchup_models.Theme `protobuf:"bytes,1,opt,name=theme" json:"theme,omitempty"`
	Ref              *string               `protobuf:"bytes,2,opt,name=ref" json:"ref,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *GetThemeResponse) Reset()                    { *m = GetThemeResponse{} }
func (m *GetThemeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetThemeResponse) ProtoMessage()               {}
func (*GetThemeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetThemeResponse) GetTheme() *ketchup_models.Theme {
	if m != nil {
		return m.Theme
	}
	return nil
}

func (m *GetThemeResponse) GetRef() string {
	if m != nil && m.Ref != nil {
		return *m.Ref
	}
	return ""
}

type UpdateDataRequest struct {
	Data             []*ketchup_models.Data `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *UpdateDataRequest) Reset()                    { *m = UpdateDataRequest{} }
func (m *UpdateDataRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateDataRequest) ProtoMessage()               {}
func (*UpdateDataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *UpdateDataRequest) GetData() []*ketchup_models.Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListDataResponse struct {
	Data             []*ketchup_models.Data `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *ListDataResponse) Reset()                    { *m = ListDataResponse{} }
func (m *ListDataResponse) String() string            { return proto.CompactTextString(m) }
func (*ListDataResponse) ProtoMessage()               {}
func (*ListDataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ListDataResponse) GetData() []*ketchup_models.Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type TLSSettingsResponse struct {
	TlsEmail         *string `protobuf:"bytes,1,opt,name=tls_email,json=tlsEmail" json:"tls_email,omitempty"`
	TlsDomain        *string `protobuf:"bytes,2,opt,name=tls_domain,json=tlsDomain" json:"tls_domain,omitempty"`
	AgreedOn         *string `protobuf:"bytes,3,opt,name=agreed_on,json=agreedOn" json:"agreed_on,omitempty"`
	TermsOfService   *string `protobuf:"bytes,4,opt,name=terms_of_service,json=termsOfService" json:"terms_of_service,omitempty"`
	HasCertificate   *bool   `protobuf:"varint,5,opt,name=has_certificate,json=hasCertificate" json:"has_certificate,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TLSSettingsResponse) Reset()                    { *m = TLSSettingsResponse{} }
func (m *TLSSettingsResponse) String() string            { return proto.CompactTextString(m) }
func (*TLSSettingsResponse) ProtoMessage()               {}
func (*TLSSettingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *TLSSettingsResponse) GetTlsEmail() string {
	if m != nil && m.TlsEmail != nil {
		return *m.TlsEmail
	}
	return ""
}

func (m *TLSSettingsResponse) GetTlsDomain() string {
	if m != nil && m.TlsDomain != nil {
		return *m.TlsDomain
	}
	return ""
}

func (m *TLSSettingsResponse) GetAgreedOn() string {
	if m != nil && m.AgreedOn != nil {
		return *m.AgreedOn
	}
	return ""
}

func (m *TLSSettingsResponse) GetTermsOfService() string {
	if m != nil && m.TermsOfService != nil {
		return *m.TermsOfService
	}
	return ""
}

func (m *TLSSettingsResponse) GetHasCertificate() bool {
	if m != nil && m.HasCertificate != nil {
		return *m.HasCertificate
	}
	return false
}

type EnableTLSRequest struct {
	TlsEmail         *string `protobuf:"bytes,1,opt,name=tls_email,json=tlsEmail" json:"tls_email,omitempty"`
	TlsDomain        *string `protobuf:"bytes,2,opt,name=tls_domain,json=tlsDomain" json:"tls_domain,omitempty"`
	Agreed           *bool   `protobuf:"varint,3,opt,name=agreed" json:"agreed,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnableTLSRequest) Reset()                    { *m = EnableTLSRequest{} }
func (m *EnableTLSRequest) String() string            { return proto.CompactTextString(m) }
func (*EnableTLSRequest) ProtoMessage()               {}
func (*EnableTLSRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *EnableTLSRequest) GetTlsEmail() string {
	if m != nil && m.TlsEmail != nil {
		return *m.TlsEmail
	}
	return ""
}

func (m *EnableTLSRequest) GetTlsDomain() string {
	if m != nil && m.TlsDomain != nil {
		return *m.TlsDomain
	}
	return ""
}

func (m *EnableTLSRequest) GetAgreed() bool {
	if m != nil && m.Agreed != nil {
		return *m.Agreed
	}
	return false
}

type CheckThemeForUpdateResponse struct {
	OldRef           *string `protobuf:"bytes,1,opt,name=old_ref,json=oldRef" json:"old_ref,omitempty"`
	CurrentRef       *string `protobuf:"bytes,2,opt,name=current_ref,json=currentRef" json:"current_ref,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CheckThemeForUpdateResponse) Reset()                    { *m = CheckThemeForUpdateResponse{} }
func (m *CheckThemeForUpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckThemeForUpdateResponse) ProtoMessage()               {}
func (*CheckThemeForUpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CheckThemeForUpdateResponse) GetOldRef() string {
	if m != nil && m.OldRef != nil {
		return *m.OldRef
	}
	return ""
}

func (m *CheckThemeForUpdateResponse) GetCurrentRef() string {
	if m != nil && m.CurrentRef != nil {
		return *m.CurrentRef
	}
	return ""
}

type InstallThemeRequest struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	VcsUrl           *string `protobuf:"bytes,2,opt,name=vcs_url,json=vcsUrl" json:"vcs_url,omitempty"`
	RegistryUrl      *string `protobuf:"bytes,3,opt,name=registry_url,json=registryUrl" json:"registry_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InstallThemeRequest) Reset()                    { *m = InstallThemeRequest{} }
func (m *InstallThemeRequest) String() string            { return proto.CompactTextString(m) }
func (*InstallThemeRequest) ProtoMessage()               {}
func (*InstallThemeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *InstallThemeRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *InstallThemeRequest) GetVcsUrl() string {
	if m != nil && m.VcsUrl != nil {
		return *m.VcsUrl
	}
	return ""
}

func (m *InstallThemeRequest) GetRegistryUrl() string {
	if m != nil && m.RegistryUrl != nil {
		return *m.RegistryUrl
	}
	return ""
}

type UpdateThemeRequest struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Ref              *string `protobuf:"bytes,2,opt,name=ref" json:"ref,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateThemeRequest) Reset()                    { *m = UpdateThemeRequest{} }
func (m *UpdateThemeRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateThemeRequest) ProtoMessage()               {}
func (*UpdateThemeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *UpdateThemeRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UpdateThemeRequest) GetRef() string {
	if m != nil && m.Ref != nil {
		return *m.Ref
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "ketchup.api.Error")
	proto.RegisterType((*FieldError)(nil), "ketchup.api.FieldError")
	proto.RegisterType((*ListOptions)(nil), "ketchup.api.ListOptions")
	proto.RegisterType((*UpdatePageRoutesRequest)(nil), "ketchup.api.UpdatePageRoutesRequest")
	proto.RegisterType((*GetRenderedPageRequest)(nil), "ketchup.api.GetRenderedPageRequest")
	proto.RegisterType((*GetRenderedPageRequest_RenderedPageOptions)(nil), "ketchup.api.GetRenderedPageRequest.RenderedPageOptions")
	proto.RegisterType((*GetRenderedPageResponse)(nil), "ketchup.api.GetRenderedPageResponse")
	proto.RegisterType((*ListPageRequest)(nil), "ketchup.api.ListPageRequest")
	proto.RegisterType((*ListPageRequest_ListPageOptions)(nil), "ketchup.api.ListPageRequest.ListPageOptions")
	proto.RegisterType((*ListPageResponse)(nil), "ketchup.api.ListPageResponse")
	proto.RegisterType((*ListRouteRequest)(nil), "ketchup.api.ListRouteRequest")
	proto.RegisterType((*ListRouteRequest_ListRouteOptions)(nil), "ketchup.api.ListRouteRequest.ListRouteOptions")
	proto.RegisterType((*ListRouteResponse)(nil), "ketchup.api.ListRouteResponse")
	proto.RegisterType((*ListThemeResponse)(nil), "ketchup.api.ListThemeResponse")
	proto.RegisterType((*GetThemeResponse)(nil), "ketchup.api.GetThemeResponse")
	proto.RegisterType((*UpdateDataRequest)(nil), "ketchup.api.UpdateDataRequest")
	proto.RegisterType((*ListDataResponse)(nil), "ketchup.api.ListDataResponse")
	proto.RegisterType((*TLSSettingsResponse)(nil), "ketchup.api.TLSSettingsResponse")
	proto.RegisterType((*EnableTLSRequest)(nil), "ketchup.api.EnableTLSRequest")
	proto.RegisterType((*CheckThemeForUpdateResponse)(nil), "ketchup.api.CheckThemeForUpdateResponse")
	proto.RegisterType((*InstallThemeRequest)(nil), "ketchup.api.InstallThemeRequest")
	proto.RegisterType((*UpdateThemeRequest)(nil), "ketchup.api.UpdateThemeRequest")
	proto.RegisterEnum("ketchup.api.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("ketchup.api.GetRenderedPageRequest_RenderedPageFilter", GetRenderedPageRequest_RenderedPageFilter_name, GetRenderedPageRequest_RenderedPageFilter_value)
	proto.RegisterEnum("ketchup.api.ListPageRequest_ListPageFilter", ListPageRequest_ListPageFilter_name, ListPageRequest_ListPageFilter_value)
}
func (m *Error) SetCode(v *ErrorCode) {
	m.Code = v
}

func (m *Error) SetTitle(v *string) {
	m.Title = v
}

func (m *Error) SetDetail(v *string) {
	m.Detail = v
}

func (m *Error) SetFields(v []*FieldError) {
	m.Fields = v
}

func (m *FieldError) SetField(v *string) {
	m.Field = v
}

func (m *FieldError) SetCode(v *string) {
	m.Code = v
}

func (m *FieldError) SetTitle(v *string) {
	m.Title = v
}

func (m *FieldError) SetDetail(v *string) {
	m.Detail = v
}

func (m *UpdatePageRoutesRequest) SetRoutes(v []*ketchup_models.Route) {
	m.Routes = v
}

func (m *GetRenderedPageRequest) SetOptions(v *GetRenderedPageRequest_RenderedPageOptions) {
	m.Options = v
}

func (m *GetRenderedPageResponse) SetData(v *structpb.Struct) {
	m.Data = v
}

func (m *ListPageRequest) SetList(v *ListOptions) {
	m.List = v
}

func (m *ListPageRequest) SetOptions(v *ListPageRequest_ListPageOptions) {
	m.Options = v
}

func (m *ListPageResponse) SetPages(v []*ketchup_models.Page) {
	m.Pages = v
}

func (m *ListRouteRequest) SetList(v *ListOptions) {
	m.List = v
}

func (m *ListRouteRequest) SetOptions(v *ListRouteRequest_ListRouteOptions) {
	m.Options = v
}

func (m *ListRouteResponse) SetRoutes(v []*ketchup_models.Route) {
	m.Routes = v
}

func (m *ListThemeResponse) SetThemes(v []*ketchup_models.Theme) {
	m.Themes = v
}

func (m *GetThemeResponse) SetTheme(v *ketchup_models.Theme) {
	m.Theme = v
}

func (m *GetThemeResponse) SetRef(v *string) {
	m.Ref = v
}

func (m *UpdateDataRequest) SetData(v []*ketchup_models.Data) {
	m.Data = v
}

func (m *ListDataResponse) SetData(v []*ketchup_models.Data) {
	m.Data = v
}

func (m *TLSSettingsResponse) SetTlsEmail(v *string) {
	m.TlsEmail = v
}

func (m *TLSSettingsResponse) SetTlsDomain(v *string) {
	m.TlsDomain = v
}

func (m *TLSSettingsResponse) SetAgreedOn(v *string) {
	m.AgreedOn = v
}

func (m *TLSSettingsResponse) SetTermsOfService(v *string) {
	m.TermsOfService = v
}

func (m *TLSSettingsResponse) SetHasCertificate(v *bool) {
	m.HasCertificate = v
}

func (m *EnableTLSRequest) SetTlsEmail(v *string) {
	m.TlsEmail = v
}

func (m *EnableTLSRequest) SetTlsDomain(v *string) {
	m.TlsDomain = v
}

func (m *EnableTLSRequest) SetAgreed(v *bool) {
	m.Agreed = v
}

func (m *CheckThemeForUpdateResponse) SetOldRef(v *string) {
	m.OldRef = v
}

func (m *CheckThemeForUpdateResponse) SetCurrentRef(v *string) {
	m.CurrentRef = v
}

func (m *InstallThemeRequest) SetName(v *string) {
	m.Name = v
}

func (m *InstallThemeRequest) SetVcsUrl(v *string) {
	m.VcsUrl = v
}

func (m *InstallThemeRequest) SetRegistryUrl(v *string) {
	m.RegistryUrl = v
}

func (m *UpdateThemeRequest) SetName(v *string) {
	m.Name = v
}

func (m *UpdateThemeRequest) SetRef(v *string) {
	m.Ref = v
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 913 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x96, 0x7f, 0x13, 0x1f, 0xb7, 0xe9, 0x76, 0xd2, 0x26, 0x26, 0x11, 0x22, 0xec, 0x0d, 0x56,
	0x52, 0x5c, 0x29, 0x48, 0x54, 0x42, 0x80, 0x44, 0x63, 0xbb, 0x8d, 0x14, 0xd9, 0x74, 0x1c, 0x97,
	0xcb, 0xd5, 0x64, 0xf7, 0xac, 0xbd, 0xea, 0x78, 0xd7, 0xcc, 0xcc, 0x46, 0xe2, 0x19, 0xb8, 0x43,
	0xbc, 0x0d, 0x57, 0xbc, 0x19, 0x9a, 0x9f, 0xb5, 0x37, 0x76, 0x2a, 0x52, 0xb8, 0xf3, 0xf9, 0xfb,
	0xce, 0x37, 0xdf, 0x39, 0x7b, 0x64, 0x68, 0xb1, 0x65, 0xd2, 0x5b, 0x8a, 0x4c, 0x65, 0xa4, 0xfd,
	0x01, 0x55, 0x38, 0xcf, 0x97, 0x3d, 0xb6, 0x4c, 0x8e, 0x60, 0xc9, 0x66, 0x68, 0x03, 0x47, 0x6d,
	0x91, 0xe5, 0x6a, 0x65, 0xa8, 0x39, 0x2e, 0x0a, 0xe3, 0x91, 0x54, 0x22, 0x0f, 0x95, 0xb3, 0x20,
	0x62, 0x8a, 0xd9, 0xdf, 0xfe, 0x1f, 0x15, 0x68, 0x0c, 0x84, 0xc8, 0x04, 0x39, 0x85, 0x7a, 0x98,
	0x45, 0xd8, 0xa9, 0x9c, 0x54, 0xba, 0x7b, 0xe7, 0x07, 0xbd, 0x52, 0x97, 0x9e, 0xc9, 0xb8, 0xc8,
	0x22, 0xa4, 0x26, 0x87, 0x3c, 0x83, 0x86, 0x4a, 0x14, 0xc7, 0x4e, 0xf5, 0xa4, 0xd2, 0x6d, 0x51,
	0x6b, 0x90, 0x03, 0x68, 0x46, 0xa8, 0x58, 0xc2, 0x3b, 0x35, 0xe3, 0x76, 0x16, 0x79, 0x09, 0xcd,
	0x38, 0x41, 0x1e, 0xc9, 0x4e, 0xfd, 0xa4, 0xd6, 0x6d, 0x9f, 0x1f, 0xde, 0xc1, 0x1e, 0xea, 0x90,
	0x69, 0x40, 0x5d, 0x9a, 0x1f, 0x01, 0xac, 0xbd, 0xba, 0x99, 0xf1, 0x1b, 0x66, 0x2d, 0x6a, 0x0d,
	0x42, 0x1c, 0x5d, 0xcb, 0x60, 0x83, 0x56, 0xed, 0x7e, 0x5a, 0xf5, 0x32, 0x2d, 0xff, 0x31, 0xb4,
	0xaf, 0x12, 0xa9, 0xc6, 0x4b, 0x95, 0x64, 0xa9, 0xf4, 0xdf, 0xc2, 0xe1, 0x74, 0x19, 0x31, 0x85,
	0x3f, 0xb3, 0x19, 0x52, 0xad, 0xa4, 0xa4, 0xf8, 0x6b, 0x8e, 0x52, 0x91, 0xaf, 0xa1, 0x69, 0xa4,
	0x95, 0x9d, 0x8a, 0x79, 0xc0, 0xf3, 0xd5, 0x03, 0x16, 0x59, 0x84, 0x5c, 0xf6, 0x4c, 0x3a, 0x75,
	0x49, 0xfe, 0xef, 0x55, 0x38, 0x78, 0x83, 0x8a, 0x62, 0x1a, 0xa1, 0xc0, 0xc8, 0xe0, 0x39, 0xa4,
	0x77, 0xb0, 0x93, 0xd9, 0x7e, 0xe6, 0x35, 0xed, 0xf3, 0x57, 0x77, 0xb4, 0xb8, 0xbf, 0xaa, 0x57,
	0xf6, 0x39, 0xba, 0xb4, 0xc0, 0x39, 0x42, 0xd8, 0xbf, 0x27, 0x4e, 0x46, 0x5a, 0x74, 0xae, 0x50,
	0xb8, 0x81, 0x7e, 0xfb, 0xa9, 0x8d, 0x86, 0xa6, 0x9a, 0x3a, 0x14, 0xff, 0x15, 0x90, 0xed, 0x28,
	0xd9, 0x81, 0x1a, 0xe3, 0xdc, 0xab, 0x90, 0xc7, 0xd0, 0x5a, 0xe6, 0x37, 0x3c, 0x91, 0x73, 0x8c,
	0xbc, 0x2a, 0x69, 0x41, 0x23, 0x12, 0x2c, 0x56, 0x5e, 0xcd, 0x1f, 0xc2, 0xe1, 0x56, 0x37, 0xb9,
	0xcc, 0x52, 0x89, 0xe4, 0x0c, 0xea, 0x7a, 0x15, 0x9d, 0x14, 0x87, 0xbd, 0x59, 0x96, 0xcd, 0xb8,
	0xdb, 0xd9, 0x9b, 0x3c, 0xee, 0x4d, 0xcc, 0xd6, 0x52, 0x93, 0xe4, 0xff, 0x59, 0x85, 0x27, 0x7a,
	0x5e, 0x65, 0x39, 0x5f, 0x40, 0x9d, 0x27, 0x52, 0x39, 0x80, 0xce, 0x9d, 0x27, 0x96, 0x66, 0x4b,
	0x4d, 0x16, 0x19, 0xae, 0xc5, 0xaf, 0x9a, 0x82, 0x17, 0x5b, 0x05, 0x65, 0x31, 0x0a, 0x7b, 0x4b,
	0xf1, 0xf7, 0x6b, 0x22, 0x85, 0xda, 0x17, 0x1b, 0x6a, 0x9f, 0x3d, 0x08, 0x79, 0x43, 0xe2, 0x6f,
	0x60, 0xef, 0x6e, 0xe4, 0x21, 0xf2, 0xfe, 0x08, 0xde, 0x1a, 0xde, 0xe9, 0x7a, 0x0a, 0x0d, 0x7d,
	0x16, 0x8a, 0x75, 0x7d, 0xb6, 0xb9, 0xae, 0x26, 0xd9, 0xa6, 0xf8, 0x7f, 0x55, 0x2c, 0x80, 0x5d,
	0xe1, 0xff, 0xa4, 0xeb, 0xdb, 0x4d, 0x5d, 0x7b, 0x5b, 0x05, 0x65, 0xf4, 0xb5, 0x63, 0x4b, 0xd9,
	0x97, 0x25, 0x2e, 0x85, 0xb4, 0xc7, 0xd0, 0xd2, 0x4c, 0x83, 0x3c, 0x4f, 0x8a, 0x13, 0xb0, 0xab,
	0x1d, 0xd3, 0x3c, 0x89, 0xfc, 0xd7, 0xf0, 0xb4, 0x04, 0xef, 0x9e, 0xff, 0x89, 0x9f, 0xab, 0xc3,
	0xb8, 0xd6, 0xf7, 0xb2, 0x8c, 0x61, 0x0e, 0xe8, 0x47, 0x31, 0x6c, 0xba, 0x4b, 0xf2, 0xdf, 0x81,
	0xf7, 0x06, 0x37, 0x20, 0xce, 0xa0, 0x61, 0xa2, 0x4e, 0xc5, 0x8f, 0x20, 0xd8, 0x1c, 0xe2, 0x41,
	0x4d, 0x60, 0xec, 0xae, 0x99, 0xfe, 0xe9, 0xff, 0x00, 0x4f, 0xed, 0x3d, 0xea, 0x33, 0xc5, 0x8a,
	0xc1, 0x74, 0x57, 0x5f, 0xcc, 0xbd, 0x83, 0x35, 0xa9, 0xf6, 0x73, 0xf9, 0xde, 0x4a, 0x69, 0x8b,
	0x1d, 0xa3, 0x87, 0x57, 0xff, 0x5d, 0x81, 0xfd, 0xeb, 0xab, 0xc9, 0x04, 0x95, 0x4a, 0xd2, 0x99,
	0x5c, 0x21, 0x1c, 0x43, 0x4b, 0x71, 0x19, 0xe0, 0x42, 0x9f, 0x53, 0x37, 0x0c, 0xc5, 0xe5, 0x40,
	0xdb, 0xe4, 0x73, 0x00, 0x1d, 0x8c, 0xb2, 0x05, 0x4b, 0x52, 0xf7, 0x14, 0x9d, 0xde, 0x37, 0x0e,
	0x5d, 0xcb, 0x66, 0x02, 0x31, 0x0a, 0xb2, 0xd4, 0x5d, 0xe8, 0x5d, 0xeb, 0x18, 0xa7, 0xa4, 0x0b,
	0x9e, 0x42, 0xb1, 0x90, 0x41, 0x16, 0x07, 0x12, 0xc5, 0x6d, 0x12, 0xa2, 0x3b, 0xd7, 0x7b, 0xc6,
	0x3f, 0x8e, 0x27, 0xd6, 0x4b, 0xbe, 0x82, 0x27, 0x73, 0x26, 0x83, 0x10, 0x85, 0x4a, 0xe2, 0x24,
	0x64, 0x0a, 0x3b, 0x8d, 0x93, 0x4a, 0x77, 0x97, 0xee, 0xcd, 0x99, 0xbc, 0x58, 0x7b, 0xfd, 0x18,
	0xbc, 0x41, 0xca, 0x6e, 0x38, 0x5e, 0x5f, 0x4d, 0x0a, 0xfd, 0xfe, 0x0f, 0xff, 0x03, 0x68, 0x5a,
	0xba, 0x86, 0xfc, 0x2e, 0x75, 0x96, 0xff, 0x0b, 0x1c, 0x5f, 0xcc, 0x31, 0xfc, 0x60, 0xe6, 0x39,
	0xcc, 0x84, 0x9d, 0xda, 0x4a, 0xb2, 0x43, 0xd8, 0xc9, 0x78, 0x14, 0xe8, 0xe9, 0xda, 0x86, 0xcd,
	0x8c, 0x47, 0x14, 0x63, 0xf2, 0x05, 0xb4, 0xc3, 0x5c, 0x08, 0x4c, 0x55, 0xb0, 0x1e, 0x3d, 0x38,
	0x17, 0xc5, 0xd8, 0x47, 0xd8, 0xbf, 0x4c, 0xa5, 0x62, 0x9c, 0xbb, 0xc5, 0xb2, 0x6f, 0x20, 0x50,
	0x4f, 0x99, 0x5b, 0xab, 0x16, 0x35, 0xbf, 0x75, 0x93, 0xdb, 0x50, 0x06, 0xb9, 0xe0, 0x0e, 0xa7,
	0x79, 0x1b, 0xca, 0xa9, 0xe0, 0xe4, 0x4b, 0x78, 0x24, 0x70, 0x96, 0x48, 0x25, 0x7e, 0x33, 0x51,
	0xab, 0x7b, 0xbb, 0xf0, 0x4d, 0x05, 0xf7, 0xbf, 0x03, 0x62, 0x29, 0xff, 0x6b, 0x97, 0xad, 0x25,
	0x3d, 0xed, 0x43, 0x6b, 0xf5, 0xdf, 0x80, 0x7c, 0x06, 0xcf, 0x2f, 0x47, 0xd7, 0x03, 0x3a, 0xfa,
	0xe9, 0x2a, 0x98, 0x0c, 0xe8, 0xfb, 0x01, 0x0d, 0x06, 0x94, 0x8e, 0xa9, 0xbd, 0x5f, 0xa3, 0xf1,
	0x75, 0x30, 0x1c, 0x4f, 0x47, 0x7d, 0xaf, 0xaa, 0xcd, 0xe1, 0x98, 0xbe, 0xbe, 0xec, 0xf7, 0x07,
	0x23, 0xaf, 0xf6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x39, 0x0e, 0x1f, 0xdd, 0x08, 0x00,
	0x00,
}
