// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto
	metadata.proto
	page.proto
	route.proto
	user.proto

It has these top-level messages:
	Error
	FieldError
	ListPageResponse
	ListRouteResponse
	Metadata
	PageTemplate
	Page
	Content
	Route
	User
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import press_models "github.com/octavore/press/proto/press/models"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ErrorCode int32

const (
	ErrorCode_INTERNAL_SERVER_ERROR ErrorCode = 1
	ErrorCode_NOT_FOUND             ErrorCode = 2
	ErrorCode_FORBIDDEN             ErrorCode = 3
)

var ErrorCode_name = map[int32]string{
	1: "INTERNAL_SERVER_ERROR",
	2: "NOT_FOUND",
	3: "FORBIDDEN",
}
var ErrorCode_value = map[string]int32{
	"INTERNAL_SERVER_ERROR": 1,
	"NOT_FOUND":             2,
	"FORBIDDEN":             3,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Error struct {
	Code             *ErrorCode    `protobuf:"varint,1,opt,name=code,enum=press.api.ErrorCode" json:"code,omitempty"`
	Title            *string       `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Detail           *string       `protobuf:"bytes,3,opt,name=detail" json:"detail,omitempty"`
	Fields           []*FieldError `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetCode() ErrorCode {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ErrorCode_INTERNAL_SERVER_ERROR
}

func (m *Error) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Error) GetDetail() string {
	if m != nil && m.Detail != nil {
		return *m.Detail
	}
	return ""
}

func (m *Error) GetFields() []*FieldError {
	if m != nil {
		return m.Fields
	}
	return nil
}

type FieldError struct {
	Field            *string `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Code             *string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Title            *string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Detail           *string `protobuf:"bytes,4,opt,name=detail" json:"detail,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FieldError) Reset()                    { *m = FieldError{} }
func (m *FieldError) String() string            { return proto.CompactTextString(m) }
func (*FieldError) ProtoMessage()               {}
func (*FieldError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FieldError) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

func (m *FieldError) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *FieldError) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *FieldError) GetDetail() string {
	if m != nil && m.Detail != nil {
		return *m.Detail
	}
	return ""
}

type ListPageResponse struct {
	Pages            []*press_models.Page `protobuf:"bytes,1,rep,name=pages" json:"pages,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ListPageResponse) Reset()                    { *m = ListPageResponse{} }
func (m *ListPageResponse) String() string            { return proto.CompactTextString(m) }
func (*ListPageResponse) ProtoMessage()               {}
func (*ListPageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListPageResponse) GetPages() []*press_models.Page {
	if m != nil {
		return m.Pages
	}
	return nil
}

type ListRouteResponse struct {
	Routes           []*press_models.Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ListRouteResponse) Reset()                    { *m = ListRouteResponse{} }
func (m *ListRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*ListRouteResponse) ProtoMessage()               {}
func (*ListRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListRouteResponse) GetRoutes() []*press_models.Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "press.api.Error")
	proto.RegisterType((*FieldError)(nil), "press.api.FieldError")
	proto.RegisterType((*ListPageResponse)(nil), "press.api.ListPageResponse")
	proto.RegisterType((*ListRouteResponse)(nil), "press.api.ListRouteResponse")
	proto.RegisterEnum("press.api.ErrorCode", ErrorCode_name, ErrorCode_value)
}

var fileDescriptor0 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x50, 0x4f, 0x4b, 0xfb, 0x40,
	0x14, 0x24, 0x4d, 0x5b, 0xc8, 0x2b, 0xbf, 0x1f, 0x71, 0x6d, 0x25, 0xf6, 0x54, 0x72, 0x2a, 0x8a,
	0x39, 0xf4, 0xec, 0xc1, 0x3f, 0xd9, 0x40, 0xa1, 0x24, 0xf2, 0xac, 0x5e, 0x43, 0x30, 0xab, 0x04,
	0xa2, 0x1b, 0x76, 0xd7, 0xaf, 0xe1, 0x67, 0x76, 0x77, 0xb3, 0xc6, 0x2a, 0x1e, 0x67, 0xde, 0xcc,
	0x9b, 0x61, 0x20, 0xa8, 0xba, 0x26, 0xe9, 0x04, 0x57, 0x9c, 0x04, 0x9d, 0x60, 0x52, 0x26, 0x9a,
	0x58, 0x42, 0x57, 0xbd, 0xb0, 0x9e, 0x5e, 0xce, 0x04, 0x7f, 0x57, 0x0e, 0xc4, 0x1f, 0x1e, 0x4c,
	0xa8, 0x10, 0x5c, 0x90, 0x35, 0x8c, 0x9f, 0x78, 0xcd, 0x22, 0x6f, 0xe5, 0xad, 0xff, 0x6f, 0xe6,
	0xc9, 0x60, 0x4e, 0xec, 0xfd, 0x56, 0xdf, 0xd0, 0x2a, 0xc8, 0x1c, 0x26, 0xaa, 0x51, 0x2d, 0x8b,
	0x46, 0x5a, 0x1a, 0x60, 0x0f, 0xc8, 0x09, 0x4c, 0x6b, 0xa6, 0xaa, 0xa6, 0x8d, 0x7c, 0x4b, 0x3b,
	0x44, 0x2e, 0x60, 0xfa, 0xdc, 0xb0, 0xb6, 0x96, 0xd1, 0x78, 0xe5, 0xaf, 0x67, 0x9b, 0xc5, 0xc1,
	0xe7, 0xcc, 0x1c, 0xec, 0x7b, 0x74, 0xa2, 0xb8, 0x06, 0xf8, 0x66, 0x4d, 0x94, 0xe5, 0x6d, 0x2b,
	0x1d, 0x65, 0x01, 0x21, 0xae, 0x6a, 0x9f, 0xff, 0xab, 0x94, 0xff, 0x77, 0xa9, 0xf1, 0x61, 0xa9,
	0xf8, 0x12, 0xc2, 0x5d, 0x23, 0xd5, 0x9d, 0x5e, 0x05, 0x99, 0xec, 0xf8, 0x9b, 0x64, 0x7a, 0x80,
	0x89, 0x59, 0x49, 0xea, 0x2c, 0xd3, 0x93, 0xb8, 0x9e, 0xaf, 0xfa, 0x7b, 0x2b, 0x13, 0x2b, 0xed,
	0x05, 0xf1, 0x15, 0x1c, 0x19, 0x37, 0x9a, 0x1d, 0x07, 0xfb, 0x39, 0x4c, 0xed, 0xb0, 0x5f, 0xfe,
	0xe3, 0x9f, 0xfe, 0x5e, 0xec, 0x24, 0x67, 0x29, 0x04, 0xc3, 0xaa, 0xe4, 0x14, 0x16, 0xdb, 0x7c,
	0x4f, 0x31, 0xbf, 0xde, 0x95, 0xf7, 0x14, 0x1f, 0x29, 0x96, 0x14, 0xb1, 0xc0, 0xd0, 0x23, 0xff,
	0x20, 0xc8, 0x8b, 0x7d, 0x99, 0x15, 0x0f, 0x79, 0x1a, 0x8e, 0x0c, 0xcc, 0x0a, 0xbc, 0xd9, 0xa6,
	0x29, 0xcd, 0x43, 0xff, 0x33, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x3f, 0xcb, 0x9c, 0xec, 0x01, 0x00,
	0x00,
}
