// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto
	content.proto
	metadata.proto
	page.proto
	route.proto
	theme.proto
	user.proto
	packages.proto

It has these top-level messages:
	Error
	FieldError
	UpdatePageRoutesRequest
	ListPageResponse
	ListRouteResponse
	ListThemeResponse
	TLSSettingsReponse
	EnableTLSRequest
	ContentMultiple
	ContentText
	ContentString
	Metadata
	Timestamp
	Page
	Content
	Route
	Theme
	ThemeTemplate
	ThemePlaceholder
	ThemeAsset
	User
	PackageRelease
	Package
	Registry
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import press_models "github.com/octavore/press/proto/press/models"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_INTERNAL_SERVER_ERROR ErrorCode = 1
	ErrorCode_NOT_FOUND             ErrorCode = 2
	ErrorCode_FORBIDDEN             ErrorCode = 3
)

var ErrorCode_name = map[int32]string{
	1: "INTERNAL_SERVER_ERROR",
	2: "NOT_FOUND",
	3: "FORBIDDEN",
}
var ErrorCode_value = map[string]int32{
	"INTERNAL_SERVER_ERROR": 1,
	"NOT_FOUND":             2,
	"FORBIDDEN":             3,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Error struct {
	Code             *ErrorCode    `protobuf:"varint,1,opt,name=code,enum=press.api.ErrorCode" json:"code,omitempty"`
	Title            *string       `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Detail           *string       `protobuf:"bytes,3,opt,name=detail" json:"detail,omitempty"`
	Fields           []*FieldError `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetCode() ErrorCode {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ErrorCode_INTERNAL_SERVER_ERROR
}

func (m *Error) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Error) GetDetail() string {
	if m != nil && m.Detail != nil {
		return *m.Detail
	}
	return ""
}

func (m *Error) GetFields() []*FieldError {
	if m != nil {
		return m.Fields
	}
	return nil
}

type FieldError struct {
	Field            *string `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Code             *string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Title            *string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Detail           *string `protobuf:"bytes,4,opt,name=detail" json:"detail,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FieldError) Reset()                    { *m = FieldError{} }
func (m *FieldError) String() string            { return proto.CompactTextString(m) }
func (*FieldError) ProtoMessage()               {}
func (*FieldError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FieldError) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

func (m *FieldError) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *FieldError) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *FieldError) GetDetail() string {
	if m != nil && m.Detail != nil {
		return *m.Detail
	}
	return ""
}

type UpdatePageRoutesRequest struct {
	Routes           []*press_models.Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *UpdatePageRoutesRequest) Reset()                    { *m = UpdatePageRoutesRequest{} }
func (m *UpdatePageRoutesRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePageRoutesRequest) ProtoMessage()               {}
func (*UpdatePageRoutesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdatePageRoutesRequest) GetRoutes() []*press_models.Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type ListPageResponse struct {
	Pages            []*press_models.Page `protobuf:"bytes,1,rep,name=pages" json:"pages,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ListPageResponse) Reset()                    { *m = ListPageResponse{} }
func (m *ListPageResponse) String() string            { return proto.CompactTextString(m) }
func (*ListPageResponse) ProtoMessage()               {}
func (*ListPageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListPageResponse) GetPages() []*press_models.Page {
	if m != nil {
		return m.Pages
	}
	return nil
}

type ListRouteResponse struct {
	Routes           []*press_models.Route `protobuf:"bytes,1,rep,name=routes" json:"routes,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ListRouteResponse) Reset()                    { *m = ListRouteResponse{} }
func (m *ListRouteResponse) String() string            { return proto.CompactTextString(m) }
func (*ListRouteResponse) ProtoMessage()               {}
func (*ListRouteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListRouteResponse) GetRoutes() []*press_models.Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type ListThemeResponse struct {
	Themes           []*press_models.Theme `protobuf:"bytes,1,rep,name=themes" json:"themes,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ListThemeResponse) Reset()                    { *m = ListThemeResponse{} }
func (m *ListThemeResponse) String() string            { return proto.CompactTextString(m) }
func (*ListThemeResponse) ProtoMessage()               {}
func (*ListThemeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListThemeResponse) GetThemes() []*press_models.Theme {
	if m != nil {
		return m.Themes
	}
	return nil
}

type TLSSettingsReponse struct {
	TlsEmail         *string `protobuf:"bytes,1,opt,name=tls_email,json=tlsEmail" json:"tls_email,omitempty"`
	TlsDomain        *string `protobuf:"bytes,2,opt,name=tls_domain,json=tlsDomain" json:"tls_domain,omitempty"`
	AgreedOn         *string `protobuf:"bytes,3,opt,name=agreed_on,json=agreedOn" json:"agreed_on,omitempty"`
	TermsOfService   *string `protobuf:"bytes,4,opt,name=terms_of_service,json=termsOfService" json:"terms_of_service,omitempty"`
	HasCertificate   *bool   `protobuf:"varint,5,opt,name=has_certificate,json=hasCertificate" json:"has_certificate,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TLSSettingsReponse) Reset()                    { *m = TLSSettingsReponse{} }
func (m *TLSSettingsReponse) String() string            { return proto.CompactTextString(m) }
func (*TLSSettingsReponse) ProtoMessage()               {}
func (*TLSSettingsReponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TLSSettingsReponse) GetTlsEmail() string {
	if m != nil && m.TlsEmail != nil {
		return *m.TlsEmail
	}
	return ""
}

func (m *TLSSettingsReponse) GetTlsDomain() string {
	if m != nil && m.TlsDomain != nil {
		return *m.TlsDomain
	}
	return ""
}

func (m *TLSSettingsReponse) GetAgreedOn() string {
	if m != nil && m.AgreedOn != nil {
		return *m.AgreedOn
	}
	return ""
}

func (m *TLSSettingsReponse) GetTermsOfService() string {
	if m != nil && m.TermsOfService != nil {
		return *m.TermsOfService
	}
	return ""
}

func (m *TLSSettingsReponse) GetHasCertificate() bool {
	if m != nil && m.HasCertificate != nil {
		return *m.HasCertificate
	}
	return false
}

type EnableTLSRequest struct {
	TlsEmail         *string `protobuf:"bytes,1,opt,name=tls_email,json=tlsEmail" json:"tls_email,omitempty"`
	TlsDomain        *string `protobuf:"bytes,2,opt,name=tls_domain,json=tlsDomain" json:"tls_domain,omitempty"`
	Agreed           *bool   `protobuf:"varint,3,opt,name=agreed" json:"agreed,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EnableTLSRequest) Reset()                    { *m = EnableTLSRequest{} }
func (m *EnableTLSRequest) String() string            { return proto.CompactTextString(m) }
func (*EnableTLSRequest) ProtoMessage()               {}
func (*EnableTLSRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *EnableTLSRequest) GetTlsEmail() string {
	if m != nil && m.TlsEmail != nil {
		return *m.TlsEmail
	}
	return ""
}

func (m *EnableTLSRequest) GetTlsDomain() string {
	if m != nil && m.TlsDomain != nil {
		return *m.TlsDomain
	}
	return ""
}

func (m *EnableTLSRequest) GetAgreed() bool {
	if m != nil && m.Agreed != nil {
		return *m.Agreed
	}
	return false
}

func init() {
	proto.RegisterType((*Error)(nil), "press.api.Error")
	proto.RegisterType((*FieldError)(nil), "press.api.FieldError")
	proto.RegisterType((*UpdatePageRoutesRequest)(nil), "press.api.UpdatePageRoutesRequest")
	proto.RegisterType((*ListPageResponse)(nil), "press.api.ListPageResponse")
	proto.RegisterType((*ListRouteResponse)(nil), "press.api.ListRouteResponse")
	proto.RegisterType((*ListThemeResponse)(nil), "press.api.ListThemeResponse")
	proto.RegisterType((*TLSSettingsReponse)(nil), "press.api.TLSSettingsReponse")
	proto.RegisterType((*EnableTLSRequest)(nil), "press.api.EnableTLSRequest")
	proto.RegisterEnum("press.api.ErrorCode", ErrorCode_name, ErrorCode_value)
}
func (m *Error) SetCode(v *ErrorCode) {
	m.Code = v
}

func (m *Error) SetTitle(v *string) {
	m.Title = v
}

func (m *Error) SetDetail(v *string) {
	m.Detail = v
}

func (m *Error) SetFields(v []*FieldError) {
	m.Fields = v
}

func (m *FieldError) SetField(v *string) {
	m.Field = v
}

func (m *FieldError) SetCode(v *string) {
	m.Code = v
}

func (m *FieldError) SetTitle(v *string) {
	m.Title = v
}

func (m *FieldError) SetDetail(v *string) {
	m.Detail = v
}

func (m *UpdatePageRoutesRequest) SetRoutes(v []*press_models.Route) {
	m.Routes = v
}

func (m *ListPageResponse) SetPages(v []*press_models.Page) {
	m.Pages = v
}

func (m *ListRouteResponse) SetRoutes(v []*press_models.Route) {
	m.Routes = v
}

func (m *ListThemeResponse) SetThemes(v []*press_models.Theme) {
	m.Themes = v
}

func (m *TLSSettingsReponse) SetTlsEmail(v *string) {
	m.TlsEmail = v
}

func (m *TLSSettingsReponse) SetTlsDomain(v *string) {
	m.TlsDomain = v
}

func (m *TLSSettingsReponse) SetAgreedOn(v *string) {
	m.AgreedOn = v
}

func (m *TLSSettingsReponse) SetTermsOfService(v *string) {
	m.TermsOfService = v
}

func (m *TLSSettingsReponse) SetHasCertificate(v *bool) {
	m.HasCertificate = v
}

func (m *EnableTLSRequest) SetTlsEmail(v *string) {
	m.TlsEmail = v
}

func (m *EnableTLSRequest) SetTlsDomain(v *string) {
	m.TlsDomain = v
}

func (m *EnableTLSRequest) SetAgreed(v *bool) {
	m.Agreed = v
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x14, 0x94, 0x9b, 0x26, 0x8a, 0x5f, 0x45, 0x30, 0x4b, 0x5b, 0x4c, 0x11, 0x52, 0xe4, 0x0b, 0x16,
	0x88, 0x1c, 0x7a, 0xe6, 0x00, 0x34, 0x8e, 0x54, 0x29, 0x8a, 0xd1, 0xc6, 0xe5, 0x6a, 0x2d, 0xf1,
	0x73, 0xb2, 0x92, 0xed, 0x35, 0xbb, 0x5b, 0x7e, 0x06, 0xbf, 0x89, 0x9f, 0x86, 0xf6, 0x23, 0x69,
	0x40, 0x70, 0x40, 0x1c, 0x67, 0x76, 0xde, 0xbc, 0xd1, 0x1b, 0x2d, 0x84, 0xac, 0xe7, 0xb3, 0x5e,
	0x0a, 0x2d, 0x48, 0xd8, 0x4b, 0x54, 0x6a, 0xc6, 0x7a, 0x7e, 0x05, 0x3d, 0xdb, 0xa2, 0xa3, 0xaf,
	0xce, 0xa4, 0xb8, 0xd7, 0x07, 0xa0, 0x77, 0xd8, 0x7a, 0x90, 0x7c, 0x0f, 0x60, 0x98, 0x49, 0x29,
	0x24, 0x49, 0xe1, 0x74, 0x23, 0x2a, 0x8c, 0x83, 0x69, 0x90, 0x4e, 0xae, 0xcf, 0x67, 0x07, 0xa7,
	0x99, 0x7d, 0xbf, 0x11, 0x15, 0x52, 0xab, 0x20, 0xe7, 0x30, 0xd4, 0x5c, 0x37, 0x18, 0x9f, 0x4c,
	0x83, 0x34, 0xa4, 0x0e, 0x90, 0x4b, 0x18, 0x55, 0xa8, 0x19, 0x6f, 0xe2, 0x81, 0xa5, 0x3d, 0x22,
	0x6f, 0x61, 0x54, 0x73, 0x6c, 0x2a, 0x15, 0x9f, 0x4e, 0x07, 0xe9, 0xd9, 0xf5, 0xc5, 0x91, 0xf3,
	0xc2, 0x3c, 0x58, 0x7b, 0xea, 0x45, 0x49, 0x05, 0xf0, 0xc0, 0x9a, 0x55, 0x96, 0xb7, 0xa9, 0x42,
	0xea, 0x00, 0x21, 0x3e, 0xaa, 0xdb, 0xff, 0x5b, 0xa8, 0xc1, 0x9f, 0x43, 0x9d, 0x1e, 0x87, 0x4a,
	0x16, 0xf0, 0xec, 0xae, 0xaf, 0x98, 0xc6, 0x4f, 0x6c, 0x8b, 0xd4, 0x1c, 0x47, 0x51, 0xfc, 0x7a,
	0x8f, 0x4a, 0x93, 0x37, 0x30, 0xb2, 0xd7, 0x52, 0x71, 0x60, 0xf3, 0x3e, 0xf5, 0x79, 0x5b, 0x51,
	0x61, 0xa3, 0x66, 0x56, 0x4c, 0xbd, 0x24, 0x79, 0x07, 0xd1, 0x92, 0x2b, 0x6d, 0x5d, 0x50, 0xf5,
	0xa2, 0x53, 0x48, 0x52, 0x18, 0x9a, 0xd3, 0xef, 0xe7, 0xc9, 0xaf, 0xf3, 0x56, 0xea, 0x04, 0xc9,
	0x7b, 0x78, 0x62, 0xa6, 0x9d, 0xe5, 0x7e, 0xfc, 0x9f, 0xf6, 0x7b, 0x87, 0xc2, 0x34, 0x7a, 0xec,
	0x60, 0x2b, 0xfe, 0x8b, 0x83, 0x13, 0x7b, 0x49, 0xf2, 0x23, 0x00, 0x52, 0x2c, 0xd7, 0x6b, 0xd4,
	0x9a, 0x77, 0x5b, 0x45, 0xd1, 0x79, 0xbc, 0x80, 0x50, 0x37, 0xaa, 0xc4, 0xd6, 0xdc, 0xce, 0x1d,
	0x7f, 0xac, 0x1b, 0x95, 0x19, 0x4c, 0x5e, 0x02, 0x98, 0xc7, 0x4a, 0xb4, 0x8c, 0x77, 0xbe, 0x05,
	0x23, 0x9f, 0x5b, 0xc2, 0xcc, 0xb2, 0xad, 0x44, 0xac, 0x4a, 0xd1, 0xf9, 0x3a, 0xc6, 0x8e, 0xc8,
	0x3b, 0x92, 0x42, 0xa4, 0x51, 0xb6, 0xaa, 0x14, 0x75, 0xa9, 0x50, 0x7e, 0xe3, 0x1b, 0xf4, 0xdd,
	0x4c, 0x2c, 0x9f, 0xd7, 0x6b, 0xc7, 0x92, 0x57, 0xf0, 0x78, 0xc7, 0x54, 0xb9, 0x41, 0xa9, 0x79,
	0xcd, 0x37, 0x4c, 0x63, 0x3c, 0x9c, 0x06, 0xe9, 0x98, 0x4e, 0x76, 0x4c, 0xdd, 0x3c, 0xb0, 0x49,
	0x0d, 0x51, 0xd6, 0xb1, 0x2f, 0x0d, 0x16, 0xcb, 0xf5, 0xbe, 0xc5, 0xff, 0xc9, 0x7f, 0x09, 0x23,
	0x17, 0xd7, 0x86, 0x1f, 0x53, 0x8f, 0x5e, 0xcf, 0x21, 0x3c, 0x7c, 0x05, 0xf2, 0x1c, 0x2e, 0x6e,
	0x57, 0x45, 0x46, 0x57, 0x1f, 0x96, 0xe5, 0x3a, 0xa3, 0x9f, 0x33, 0x5a, 0x66, 0x94, 0xe6, 0x34,
	0x0a, 0xc8, 0x23, 0x08, 0x57, 0x79, 0x51, 0x2e, 0xf2, 0xbb, 0xd5, 0x3c, 0x3a, 0x31, 0x70, 0x91,
	0xd3, 0x8f, 0xb7, 0xf3, 0x79, 0xb6, 0x8a, 0x06, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xc7,
	0x0b, 0xf8, 0xae, 0x03, 0x00, 0x00,
}
