// Code generated by protoc-gen-go.
// source: content.proto
// DO NOT EDIT!

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ContentTextType int32

const (
	ContentTextType_text     ContentTextType = 0
	ContentTextType_markdown ContentTextType = 1
	ContentTextType_html     ContentTextType = 2
)

var ContentTextType_name = map[int32]string{
	0: "text",
	1: "markdown",
	2: "html",
}
var ContentTextType_value = map[string]int32{
	"text":     0,
	"markdown": 1,
	"html":     2,
}

func (x ContentTextType) Enum() *ContentTextType {
	p := new(ContentTextType)
	*p = x
	return p
}
func (x ContentTextType) String() string {
	return proto.EnumName(ContentTextType_name, int32(x))
}
func (x *ContentTextType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ContentTextType_value, data, "ContentTextType")
	if err != nil {
		return err
	}
	*x = ContentTextType(value)
	return nil
}
func (ContentTextType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type ContentMultiple_DropdownType int32

const (
	ContentMultiple_unknown  ContentMultiple_DropdownType = 0
	ContentMultiple_radio    ContentMultiple_DropdownType = 1
	ContentMultiple_dropdown ContentMultiple_DropdownType = 2
)

var ContentMultiple_DropdownType_name = map[int32]string{
	0: "unknown",
	1: "radio",
	2: "dropdown",
}
var ContentMultiple_DropdownType_value = map[string]int32{
	"unknown":  0,
	"radio":    1,
	"dropdown": 2,
}

func (x ContentMultiple_DropdownType) Enum() *ContentMultiple_DropdownType {
	p := new(ContentMultiple_DropdownType)
	*p = x
	return p
}
func (x ContentMultiple_DropdownType) String() string {
	return proto.EnumName(ContentMultiple_DropdownType_name, int32(x))
}
func (x *ContentMultiple_DropdownType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ContentMultiple_DropdownType_value, data, "ContentMultiple_DropdownType")
	if err != nil {
		return err
	}
	*x = ContentMultiple_DropdownType(value)
	return nil
}
func (ContentMultiple_DropdownType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor1, []int{0, 0}
}

type ContentMultiple struct {
	Title            *string                       `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Options          []string                      `protobuf:"bytes,2,rep,name=options" json:"options,omitempty"`
	Type             *ContentMultiple_DropdownType `protobuf:"varint,3,opt,name=type,enum=press.models.ContentMultiple_DropdownType,def=2" json:"type,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *ContentMultiple) Reset()                    { *m = ContentMultiple{} }
func (m *ContentMultiple) String() string            { return proto.CompactTextString(m) }
func (*ContentMultiple) ProtoMessage()               {}
func (*ContentMultiple) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

const Default_ContentMultiple_Type ContentMultiple_DropdownType = ContentMultiple_dropdown

func (m *ContentMultiple) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *ContentMultiple) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *ContentMultiple) GetType() ContentMultiple_DropdownType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_ContentMultiple_Type
}

type ContentText struct {
	Title            *string          `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Type             *ContentTextType `protobuf:"varint,2,opt,name=type,enum=press.models.ContentTextType" json:"type,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ContentText) Reset()                    { *m = ContentText{} }
func (m *ContentText) String() string            { return proto.CompactTextString(m) }
func (*ContentText) ProtoMessage()               {}
func (*ContentText) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ContentText) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *ContentText) GetType() ContentTextType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ContentTextType_text
}

type ContentString struct {
	Title            *string          `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Type             *ContentTextType `protobuf:"varint,2,opt,name=type,enum=press.models.ContentTextType" json:"type,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ContentString) Reset()                    { *m = ContentString{} }
func (m *ContentString) String() string            { return proto.CompactTextString(m) }
func (*ContentString) ProtoMessage()               {}
func (*ContentString) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ContentString) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *ContentString) GetType() ContentTextType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ContentTextType_text
}

func init() {
	proto.RegisterType((*ContentMultiple)(nil), "press.models.ContentMultiple")
	proto.RegisterType((*ContentText)(nil), "press.models.ContentText")
	proto.RegisterType((*ContentString)(nil), "press.models.ContentString")
	proto.RegisterEnum("press.models.ContentTextType", ContentTextType_name, ContentTextType_value)
	proto.RegisterEnum("press.models.ContentMultiple_DropdownType", ContentMultiple_DropdownType_name, ContentMultiple_DropdownType_value)
}
func (m *ContentMultiple) SetTitle(v *string) {
	m.Title = v
}

func (m *ContentMultiple) SetOptions(v []string) {
	m.Options = v
}

func (m *ContentMultiple) SetType(v *ContentMultiple_DropdownType) {
	m.Type = v
}

func (m *ContentText) SetTitle(v *string) {
	m.Title = v
}

func (m *ContentText) SetType(v *ContentTextType) {
	m.Type = v
}

func (m *ContentString) SetTitle(v *string) {
	m.Title = v
}

func (m *ContentString) SetType(v *ContentTextType) {
	m.Type = v
}

func init() { proto.RegisterFile("content.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x14, 0xc4, 0xeb, 0xb4, 0x55, 0x9b, 0xd7, 0x14, 0x2c, 0x8b, 0x21, 0x0b, 0x52, 0x94, 0x29, 0xea,
	0x60, 0x89, 0x3f, 0x13, 0x2b, 0x0c, 0x2c, 0x2c, 0xa1, 0x42, 0xac, 0x15, 0xb1, 0xc0, 0xaa, 0xe3,
	0x67, 0x39, 0xaf, 0x6a, 0xfb, 0xf1, 0xf8, 0x66, 0x28, 0xa9, 0x5b, 0x45, 0x08, 0xb6, 0x8e, 0xe7,
	0xd3, 0xbb, 0xfb, 0x9d, 0x61, 0xfe, 0x81, 0x96, 0x94, 0x25, 0xe9, 0x3c, 0x12, 0x8a, 0xc4, 0x79,
	0xd5, 0x34, 0xb2, 0xc6, 0x4a, 0x99, 0x26, 0xff, 0x66, 0x70, 0xf9, 0x78, 0xf0, 0x5f, 0x36, 0x86,
	0xb4, 0x33, 0x4a, 0x5c, 0xc1, 0x98, 0x34, 0x19, 0x95, 0xb2, 0x8c, 0x15, 0x71, 0x79, 0x10, 0x22,
	0x85, 0x09, 0x3a, 0xd2, 0x68, 0x9b, 0x34, 0xca, 0x86, 0x45, 0x5c, 0x1e, 0xa5, 0x78, 0x86, 0x11,
	0xed, 0x9d, 0x4a, 0x87, 0x19, 0x2b, 0x2e, 0x6e, 0x17, 0xb2, 0x5f, 0x20, 0x7f, 0x85, 0xcb, 0x27,
	0x8f, 0xae, 0xc2, 0xad, 0x5d, 0xee, 0x9d, 0x7a, 0x98, 0x56, 0x41, 0x95, 0x5d, 0x42, 0x7e, 0x0f,
	0x49, 0xdf, 0x17, 0x33, 0x98, 0x6c, 0xec, 0xda, 0xe2, 0xd6, 0xf2, 0x81, 0x88, 0x61, 0xec, 0x57,
	0x95, 0x46, 0xce, 0x44, 0x02, 0xa7, 0x4b, 0x1e, 0xe5, 0x6f, 0x30, 0x0b, 0x2d, 0x4b, 0xb5, 0xa3,
	0x7f, 0xf0, 0x6f, 0x02, 0x64, 0xd4, 0x41, 0x5e, 0xff, 0x09, 0xd9, 0x9e, 0xb7, 0xbd, 0x81, 0xe6,
	0x1d, 0xe6, 0xc1, 0x78, 0x25, 0xaf, 0xed, 0xe7, 0xd9, 0x92, 0x17, 0x77, 0xa7, 0x4f, 0x3f, 0x1a,
	0x62, 0x0a, 0x23, 0x52, 0x3b, 0xe2, 0x83, 0x76, 0x5c, 0xbd, 0xf2, 0xeb, 0x6e, 0x1c, 0x6b, 0xdf,
	0xbf, 0xa8, 0x36, 0x3c, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0x12, 0x06, 0x10, 0xd7, 0xc8, 0x01,
	0x00, 0x00,
}
