// Code generated by protoc-gen-go.
// source: page.proto
// DO NOT EDIT!

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Content_ContentType int32

const (
	Content_unknown  Content_ContentType = 0
	Content_html     Content_ContentType = 1
	Content_markdown Content_ContentType = 2
)

var Content_ContentType_name = map[int32]string{
	0: "unknown",
	1: "html",
	2: "markdown",
}
var Content_ContentType_value = map[string]int32{
	"unknown":  0,
	"html":     1,
	"markdown": 2,
}

func (x Content_ContentType) Enum() *Content_ContentType {
	p := new(Content_ContentType)
	*p = x
	return p
}
func (x Content_ContentType) String() string {
	return proto.EnumName(Content_ContentType_name, int32(x))
}
func (x *Content_ContentType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Content_ContentType_value, data, "Content_ContentType")
	if err != nil {
		return err
	}
	*x = Content_ContentType(value)
	return nil
}
func (Content_ContentType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 0} }

type Page struct {
	Uuid             *string           `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Name             *string           `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Theme            *string           `protobuf:"bytes,3,opt,name=theme" json:"theme,omitempty"`
	Template         *string           `protobuf:"bytes,4,opt,name=template" json:"template,omitempty"`
	Contents         []*Content        `protobuf:"bytes,10,rep,name=contents" json:"contents,omitempty"`
	Metadata         map[string]string `protobuf:"bytes,11,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags             []string          `protobuf:"bytes,12,rep,name=tags" json:"tags,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Page) Reset()                    { *m = Page{} }
func (m *Page) String() string            { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()               {}
func (*Page) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Page) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *Page) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Page) GetTheme() string {
	if m != nil && m.Theme != nil {
		return *m.Theme
	}
	return ""
}

func (m *Page) GetTemplate() string {
	if m != nil && m.Template != nil {
		return *m.Template
	}
	return ""
}

func (m *Page) GetContents() []*Content {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Page) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Page) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// versioned?
type Content struct {
	Uuid             *string              `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	ContentType      *Content_ContentType `protobuf:"varint,2,opt,name=contentType,enum=press.models.Content_ContentType" json:"contentType,omitempty"`
	Key              *string              `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Value            *string              `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Content) Reset()                    { *m = Content{} }
func (m *Content) String() string            { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()               {}
func (*Content) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *Content) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *Content) GetContentType() Content_ContentType {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return Content_unknown
}

func (m *Content) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Content) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Page)(nil), "press.models.Page")
	proto.RegisterType((*Content)(nil), "press.models.Content")
	proto.RegisterEnum("press.models.Content_ContentType", Content_ContentType_name, Content_ContentType_value)
}

var fileDescriptor2 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0x84, 0x50,
	0x14, 0xc6, 0xf3, 0x4f, 0x8c, 0x1d, 0xa7, 0x90, 0x43, 0xc1, 0x65, 0x56, 0xe6, 0x6a, 0x56, 0x42,
	0xae, 0xa2, 0xda, 0x0d, 0x2d, 0x83, 0x90, 0x5e, 0xe0, 0x92, 0x87, 0x99, 0x50, 0xaf, 0xa2, 0xc7,
	0xc2, 0xd7, 0xe9, 0x41, 0x7a, 0xb6, 0xbc, 0xfe, 0xc3, 0x01, 0x57, 0x9e, 0xf3, 0x9d, 0xef, 0x93,
	0xdf, 0x77, 0x01, 0x4a, 0x79, 0xa4, 0xb0, 0xac, 0x0a, 0x2e, 0x70, 0x5b, 0x56, 0x54, 0xd7, 0x61,
	0x5e, 0x24, 0x94, 0xd5, 0xc1, 0xaf, 0x09, 0xf6, 0x7b, 0x77, 0x44, 0x04, 0xbb, 0x69, 0xbe, 0x12,
	0x61, 0xf8, 0xc6, 0xfe, 0x2a, 0xee, 0x67, 0xad, 0x29, 0x99, 0x93, 0x30, 0x07, 0x4d, 0xcf, 0x78,
	0x0b, 0x97, 0x7c, 0xa2, 0x4e, 0xb4, 0x7a, 0x71, 0x58, 0x70, 0x07, 0x0e, 0x53, 0x5e, 0x66, 0x92,
	0x49, 0xd8, 0xfd, 0x61, 0xde, 0xf1, 0x01, 0x9c, 0xcf, 0x42, 0x31, 0x29, 0xae, 0x05, 0xf8, 0xd6,
	0xde, 0x8d, 0xee, 0xc2, 0x25, 0x43, 0x78, 0x18, 0xae, 0xf1, 0x6c, 0xc3, 0x17, 0x70, 0x72, 0x62,
	0x99, 0x48, 0x96, 0xc2, 0xed, 0x23, 0xfe, 0x79, 0x44, 0x23, 0x87, 0x6f, 0xa3, 0xe5, 0x55, 0x71,
	0xd5, 0xc6, 0x73, 0x42, 0x63, 0xb3, 0x3c, 0xd6, 0x62, 0xdb, 0x25, 0x3b, 0x6c, 0x3d, 0xef, 0x9e,
	0xe1, 0xfa, 0xcc, 0x8e, 0x1e, 0x58, 0x29, 0xb5, 0x63, 0x5d, 0x3d, 0xea, 0x66, 0xdf, 0x32, 0x6b,
	0xa6, 0xba, 0xc3, 0xf2, 0x64, 0x3e, 0x1a, 0xc1, 0x9f, 0x01, 0x9b, 0x11, 0x72, 0xf5, 0x9d, 0x0e,
	0xe0, 0x8e, 0xe8, 0x1f, 0x6d, 0x39, 0xe4, 0x6f, 0xa2, 0xfb, 0xd5, 0x92, 0xd3, 0x57, 0x1b, 0xe3,
	0x65, 0x6a, 0x02, 0xb2, 0x56, 0x80, 0xec, 0x05, 0x50, 0x10, 0x81, 0xbb, 0xf8, 0x07, 0xba, 0xb0,
	0x69, 0x54, 0xaa, 0x8a, 0x1f, 0xe5, 0x5d, 0xa0, 0x03, 0xf6, 0x89, 0xf3, 0xcc, 0x33, 0x70, 0xdb,
	0xbd, 0xa0, 0xac, 0xd2, 0x44, 0xeb, 0xe6, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x22, 0xdc,
	0x86, 0x00, 0x02, 0x00, 0x00,
}
